[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"
[functions."bets-scheduled-function"]
schedule = "*/10 * * * *"
[functions."events-scheduled-function"]
schedule = "*/10 * * * *"
[functions."players-scheduled-function"]
schedule = "*/10 * * * *"