[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"
[functions."cron-scheduled-function"]
schedule = "*/5 * * * *"
[functions."bets-cron-scheduled-function"]
schedule = "*/10 * * * *"